def writeSdf(path, p, w, s, mu1, mu2):
    f = open(path, "a")
    f.write("<?xml version=\"1.0\"?>")
    f.write("\n")
    f.write("<sdf version='1.7'>")
    f.write("\n")
    f.write("  <model name='unit_box'>")
    f.write("\n")
    f.write("  <pose>" + str(p[0]) + " " + str(p[1]) + " " + str(p[2]) + " 0 0 0</pose>")
    f.write("\n")
    f.write("    <link name='link'>")
    f.write("\n")
    f.write("      <inertial>")
    f.write("\n")
    f.write("        <mass>" + str(w) + "</mass>")
    f.write("\n")
    f.write("        <inertia>")
    f.write("\n")
    f.write("          <ixx>1.</ixx>")
    f.write("\n")
    f.write("          <ixy>0</ixy>")
    f.write("\n")
    f.write("          <ixz>0</ixz>")
    f.write("\n")
    f.write("          <iyy>1.</iyy>")
    f.write("\n")
    f.write("          <iyz>0</iyz>")
    f.write("\n")
    f.write("          <izz>1.</izz>")
    f.write("\n")
    f.write("        </inertia>")
    f.write("\n")
    f.write("        <pose>0 0 0 0 0 0</pose>")
    f.write("\n")
    f.write("      </inertial>")
    f.write("\n")
    f.write("      <self_collide>1</self_collide>")
    f.write("\n")
    f.write("      <enable_wind>0</enable_wind>")
    f.write("\n")
    f.write("      <kinematic>0</kinematic>")
    f.write("\n")
    f.write("      <pose>0 0 0 0 0 0</pose>")
    f.write("\n")
    f.write("      <gravity>1</gravity>")
    f.write("\n")
    f.write("      <visual name='visual'>")
    f.write("\n")
    f.write("        <geometry>")
    f.write("\n")
    f.write("          <box>")
    f.write("\n")
    f.write("            <size>" + str(s[0]) + " " + str(s[1]) + " " + str(s[2]) + "</size>")
    f.write("\n")
    f.write("          </box>")
    f.write("\n")
    f.write("        </geometry>")
    f.write("\n")
    f.write("        <material>")
    f.write("\n")
    f.write("          <script>")
    f.write("\n")
    f.write("            <name>Gazebo/Grey</name>")
    f.write("\n")
    f.write("            <uri>file://media/materials/scripts/gazebo.material</uri>")
    f.write("\n")
    f.write("          </script>")
    f.write("\n")
    f.write("          <shader type='pixel'>")
    f.write("\n")
    f.write("            <normal_map>__default__</normal_map>")
    f.write("\n")
    f.write("          </shader>")
    f.write("\n")
    f.write("        </material>")
    f.write("\n")
    f.write("        <pose>0 0 0 0 0 0</pose>")
    f.write("\n")
    f.write("        <transparency>0</transparency>")
    f.write("\n")
    f.write("        <cast_shadows>1</cast_shadows>")
    f.write("\n")
    f.write("      </visual>")
    f.write("\n")
    f.write("      <collision name='collision'>")
    f.write("\n")
    f.write("        <laser_retro>0</laser_retro>")
    f.write("\n")
    f.write("        <max_contacts>10</max_contacts>")
    f.write("\n")
    f.write("        <pose>0 0 0 0 0 0</pose>")
    f.write("\n")
    f.write("        <geometry>")
    f.write("\n")
    f.write("          <box>")
    f.write("\n")
    f.write("            <size>" + str(s[0]) + " " + str(s[1]) + " " + str(s[2]) + "</size>")
    f.write("\n")
    f.write("          </box>")
    f.write("\n")
    f.write("        </geometry>")
    f.write("\n")
    f.write("        <surface>")
    f.write("\n")
    f.write("          <friction>")
    f.write("\n")
    f.write("            <ode>")
    f.write("\n")
    f.write("              <mu>" + str(mu1) + "</mu>")
    f.write("\n")
    f.write("              <mu2>" + str(mu2) + "</mu2>")
    f.write("\n")
    f.write("              <fdir1>0 0 0</fdir1>")
    f.write("\n")
    f.write("              <slip1>0</slip1>")
    f.write("\n")
    f.write("              <slip2>0</slip2>")
    f.write("\n")
    f.write("            </ode>")
    f.write("\n")
    f.write("            <torsional>")
    f.write("\n")
    f.write("              <coefficient>0.3</coefficient>")
    f.write("\n")
    f.write("              <patch_radius>0</patch_radius>")
    f.write("\n")
    f.write("              <surface_radius>0</surface_radius>")
    f.write("\n")
    f.write("              <use_patch_radius>1</use_patch_radius>")
    f.write("\n")
    f.write("              <ode>")
    f.write("\n")
    f.write("                <slip>0.01</slip>")
    f.write("\n")
    f.write("              </ode>")
    f.write("\n")
    f.write("            </torsional>")
    f.write("\n")
    f.write("          </friction>")
    f.write("\n")
    f.write("          <bounce>")
    f.write("\n")
    f.write("            <restitution_coefficient>0</restitution_coefficient>")
    f.write("\n")
    f.write("            <threshold>1e+03</threshold>")
    f.write("\n")
    f.write("          </bounce>")
    f.write("\n")
    f.write("          <contact>")
    f.write("\n")
    f.write("            <collide_without_contact>0</collide_without_contact>")
    f.write("\n")
    f.write("            <collide_without_contact_bitmask>1</collide_without_contact_bitmask>")
    f.write("\n")
    f.write("            <collide_bitmask>1</collide_bitmask>")
    f.write("\n")
    f.write("            <ode>")
    f.write("\n")
    f.write("              <soft_cfm>0</soft_cfm>")
    f.write("\n")
    f.write("              <soft_erp>0.2</soft_erp>")
    f.write("\n")
    f.write("              <kp>1e+11</kp>")
    f.write("\n")
    f.write("              <kd>1</kd>")
    f.write("\n")
    f.write("              <max_vel>0.01</max_vel>")
    f.write("\n")
    f.write("              <min_depth>0</min_depth>")
    f.write("\n")
    f.write("            </ode>")
    f.write("\n")
    f.write("            <bullet>")
    f.write("\n")
    f.write("              <split_impulse>1</split_impulse>")
    f.write("\n")
    f.write("              <split_impulse_penetration_threshold>-0.01</split_impulse_penetration_threshold>")
    f.write("\n")
    f.write("              <soft_cfm>0</soft_cfm>")
    f.write("\n")
    f.write("              <soft_erp>0.2</soft_erp>")
    f.write("\n")
    f.write("              <kp>1e+13</kp>")
    f.write("\n")
    f.write("              <kd>1</kd>")
    f.write("\n")
    f.write("            </bullet>")
    f.write("\n")
    f.write("          </contact>")
    f.write("\n")
    f.write("        </surface>")
    f.write("\n")
    f.write("      </collision>")
    f.write("\n")
    f.write("    </link>")
    f.write("\n")
    f.write("    <static>0</static>")
    f.write("\n")
    f.write("    <allow_auto_disable>1</allow_auto_disable>")
    f.write("\n")
    f.write("  </model>")
    f.write("\n")
    f.write("</sdf>")
    f.close()