def writeBoxes(boxes,friction):
    f = open("xmlFiles/boxes.xml", "a")
    f.write("<mujoco model=\"boxes\">")
    f.write("\n")
    f.write("\n")
    f.write("  <option timestep=\"0.002\" iterations=\"100\" solver=\"Newton\" gravity=\"0 0 -9.81\" integrator=\"RK4\"></option>")
    f.write("\n")
    f.write("\n")
    f.write("  <default>")
    f.write("\n")
    f.write("    <joint type=\"free\"/>")
    f.write("\n")
    f.write("  </default>")
    f.write("\n")
    f.write("\n")
    f.write("  <worldbody>")
    for i,x in enumerate(boxes):
        f.write("\n")
        f.write("    <body name=\"box" + str(i) + "\" pos=\"" + x[0][0] + " " + x[0][1] + " " + x[0][2] + "\">")
        f.write("\n")
        f.write("      <joint/>")
        f.write("\n")
        f.write("      <geom name=\"boxshape" + str(i) + "\" type=\"box\" size=\"" + x[1][0] + " " + x[1][1] + " " + x[1][2] + "\" mass=\"" + x[2] + "\" rgba=\"1 0 1 1\"/>")
        f.write("\n")
        f.write("    </body>")
    f.write("\n")
    f.write("\n")
    f.write("  </worldbody>")
    f.write("\n")
    f.write("\n")
    f.write("  <contact>")
    for i,x in enumerate(boxes):
        f.write("\n")
        f.write("    <pair geom1=\"body\" geom2=\"boxshape" + str(i) + "\" condim=\"6\" friction=\"" + str(friction) + " " + str(friction) + "\"/>")
        for j,y in enumerate(boxes):       
            if i < j:
                f.write("\n")
                f.write("    <pair geom1=\"boxshape" + str(i) + "\" geom2=\"boxshape" + str(j) + "\" condim=\"6\" friction=\"" + str(friction) + " " + str(friction) + "\"/>")
    f.write("\n")
    f.write("  </contact>")
    f.write("\n")
    f.write("\n")
    f.write("</mujoco>")