name: Build and push

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to the Container registry
      uses: docker/login-action@v3.3.0
      with:
        registry: ghcr.io
        username: alexandernorup
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push the Docker image
      run: | 
        cd EiTSoftBot
        docker build -t ghcr.io/alexandernorup/eitsoftbot/web:${{ github.sha }} .
        docker tag ghcr.io/alexandernorup/eitsoftbot/web:${{ github.sha }} ghcr.io/alexandernorup/eitsoftbot/web:latest
        docker push ghcr.io/alexandernorup/eitsoftbot/web --all-tags 

  deploy:
    needs: [build]
    name: "Deploy image to eit.app.alexandernorup.com"
    runs-on: ubuntu-latest
    environment: eit.app.alexandernorup.com 
    steps:
      - name: Get SSH key
        run: echo "${{secrets.SSH_KEY}}" >> ssh_key

      - name: Pull image and restart
        run: ssh -i ssh_key gh_actions@hosting.alexandernorup.com -t 'cd /home/alex/eitsoftbot;docker-compose pull;docker-compose up -d --remove-orphans;docker image prune -f'
